config/routes.rb
Rails.application.routes.draw do
  # Custom errors
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'index#index', as: 'root'
  get '/archive/:year/:month', to: 'pages#archive', as: 'archive'
  get '/category/:name', to: 'categories#show_by_name', as: 'categoryname'

  resources :users
  resources :pages do
    resources :comments
  end
  resources :categories
  resources :tags

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pages
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :page
  validates :content, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments
  has_many :parts
  has_many :tags, through: :parts
  validates :title, :content, presence: true
  self.per_page = 4
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :page
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :parts
  has_many :pages, through: :parts
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :pages
  has_many :comments
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, confirmation: true
  self.per_page = 10

  ROLES = ['admin', 'editor']

  def name
    return "#{first_name} #{last_name}"
  end

  def editor?
    self.role == 'editor'
  end

  def admin?
    self.role == 'admin'
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_owner, only: [:edit, :update, :destroy]
  helper_method :owner?
  def index
    @pages = Page.paginate(:page => params[:page])
  end
  def show
    @page = Page.find(params[:id])
    @older = Page.where('created_at < ?', @page.created_at).order('created_at DESC').take
    @newer = Page.where('created_at > ?', @page.created_at).take
  end
  def new
    @page = Page.new
  end
  def create
    @page = Page.new(page_params)
    @page.user_id = session[:user_id]
    if @page.save
      flash[:notice] = "Page created"
      redirect_to page_path @page
    else
      flash.now[:error] = "Please fix all errors"
      render 'new'
    end
  end
  def edit
    # require_owner
    render 'new'
  end
  def update
    # require_owner
    if @page.update(page_params)
      flash[:notice] = "Page updated"
      redirect_to page_path(:id => @page.id)
    else
      flash.now[:error] = "Please fix all errors"
      render 'new'
    end
  end
  def destroy
    # require_owner
    owner_id = @page.user_id
    @page.destroy
    flash[:notice] = "Page removed"
    redirect_to user_path(:id => owner_id)
  end
  def archive
    first = Date.new(params[:year].to_i, params[:month].to_i, 01)
    last = first + 1.month
    @pages = Page.where('created_at BETWEEN ? AND ?', first, last)
    @date = first.strftime('%B %Y')
  end
  private
  # Helper
  def owner? page
    if page.present?
      return page.user_id == session[:user_id]
    end
    return false
  end
  def require_owner
    @page = Page.find_by_id(params[:id])
    unless owner? @page
      flash[:error] = "Only owner can do this!"
      redirect_to pages_path
    end
  end
  def page_params
    params.require(:page).permit(:title, :content, :category_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_user, only: [:new, :edit, :update, :destroy]
  def index
    @tags = Tag.joins(:parts).group('tags.id').select('tags.id, tags.name, COUNT(*) as quantity')
  end
  def show
    @tag = Tag.find(params[:id])
    @pages = @tag.pages.paginate(:page => params[:page])
  end
  def new
    @tag = Tag.new
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == params[:sort] && params[:direction]) == "asc" ? "desc" : "asc"
    css_class = (column == params[:sort]) ? "current #{direction}" : ""
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  # Choose Boostrap class by flash type
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  # Generate flash messages with Boostrap classes
  def boostrap_flash_messages
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, role: "alert", class: "alert #{bootstrap_class_for(msg_type)} sticky-top fade show") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end

  # Generate wrapper for form fields with errors placeholder
  def bootstrap_field_wrap(record, field)
    concat(content_tag(:div, class: "form-group" <<  ( record.errors.has_key?(field) ? " has-danger" : "")) do
      concat yield
      concat content_tag(:div, record.errors.full_messages_for(field).join('<br/>'), class: "form-control-feedback")
    end)
    nil
  end
  # Link Renderer for will_paginate
  # example of usage `will_paginate @pages, class: "blog-pagination", renderer: BootstrapHelper::LinkRenderer`
	class LinkRenderer < WillPaginate::ActionView::LinkRenderer
		protected
      def page_number(page)
        unless page == current_page
          link(page, page, :rel => rel_value(page), :class => 'btn btn-outline-primary')
        else
          link(page, "#", :class => 'btn btn-outline-secondary disabled')
        end
      end
      def previous_or_next_page(page, text, classname)
        if page
          link(text, page, :class => classname + ' btn btn-outline-primary')
        else
          link(text, "#", :class => classname + ' btn btn-outline-secondary disabled')
        end
      end
      def html_container(html)
        tag(:nav, html, container_attributes)
      end
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/index.html.erb
<div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>This is my personal sandbox.</p>
  <p>Small roadmap for me:</p>
  <uL class="checklist">
    <li class="done">create simple rails application</li>
    <li class="done">with one-to-many and many-to-many relationship</li>
    <li>with nested resources (page comments)</li>
    <li class="done">with default and custom routes</li>
    <li class="done">with authorization and authentication</li>
    <li class="done">with admin dashboard</li>
    <li class="done">with page navigation</li>
    <li class="done">with simple grid</li>
    <li>with integration of WYSIWYG editor</li>
    <li>with interactive elements (AJAX for comments)</li>
    <li class="done">with tests</li>
    <li class="done">with continuous integration</li>
    <li class="done">with continuous deployment</li>
  </ul>
  <p>
    <%= link_to "Learn more", "https://github.com/AntonShevchuk/blog", class: "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/layouts/_footer.html.erb
<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= yield :title %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_navbar.html.erb
<div class="blog-masthead sticky-top">
  <div class="container">
    <nav class="navbar navbar-toggleable-md navbar-light ">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Blog</a>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav  mr-auto">
          <%= link_to "Home", root_path, class: "nav-item nav-link #{'active' if current_page? root_path}" %>
          <%= link_to "Pages", pages_path, class: "nav-item nav-link #{'active' if current_page? pages_path}" %>
          <%= link_to "Authors", users_path, class: "nav-item nav-link #{'active' if current_page? users_path}" %>
          <%= link_to "Users", admin_users_path, class: "nav-item nav-link #{'active' if current_page? admin_users_path}" if admin? %>
        </div>
        <div class="navbar-nav my-2 my-lg-0">
          <% if current_user %>
            <%= link_to current_user.name, user_path(current_user), class: "nav-item nav-link #{'active' if current_page? user_path(current_user)}"  %>
            <%= link_to "Log out", logout_path, method: "delete", class: "nav-item nav-link" %>
          <% else %>
            <%= link_to "Login", login_path, class: "nav-item nav-link #{'active' if current_page? login_path}"  %>
            <%= link_to "Signup", signup_path, class: "nav-item nav-link #{'active' if current_page? signup_path}"  %>
          <% end %>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">Admin Dashboard</h1>
        <p class="lead blog-description">Be careful with sensitive data</p>
      </div>
    </div>
    <div class="container blog-main">
          <%= boostrap_flash_messages %>
          <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">An example blog template built with Bootstrap.</p>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-8 blog-main">
          <%= boostrap_flash_messages %>
          <%= yield %>
        </div>
        <div class="col-sm-3 offset-sm-1 blog-sidebar">
          <%= yield :sidebar %>

          <% if category_data %>
          <div class="sidebar-module">
            <h4>Categories</h4>
            <ol class="list-unstyled">
              <% category_data.each do |cat| %>
              <li><%= link_to cat.name, categoryname_path(name:cat.name) %></a>
              <% end %>
            </ol>
          </div>
          <% end %>

          <% if archive_data %>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <% archive_data.each do |data| %>
              <li><%= link_to Date.new(data.year.to_i, data.month.to_i).strftime('%B %Y'), archive_path(year:data.year.to_i, month:data.month.to_i) %></a>
              <% end %>
            </ol>
          </div>
          <% end %>

          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="https://github.com/AntonShevchuk">GitHub</a></li>
              <li><a href="https://twitter.com/AntonShevchuk">Twitter</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->
      </div>
    </div> <!-- /container -->

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_index.html.erb
<% @pages.each do |page| %>
<div class="blog-post">
  <h3 class="blog-post-title"><%= link_to page.title, page_path(page) %></h3>
  <p class="blog-post-meta">
      Posted at <%= page.created_at.strftime('%B %d, %Y')%>
      by <%= link_to page.user.name, user_path(page.user) %>
      to <%= link_to page.category.name, category_path(page.category) %>
  </p>
</div>
<% end %>
<%= will_paginate @pages, class: "blog-pagination", renderer: BootstrapHelper::LinkRenderer %>

app/views/pages/_list.html.erb
<% if pages.size != 0 %>
  <ul>
    <% pages.each do |page| %>
      <li><%= link_to page.title, page_path(page) %></li>
    <% end %>
  </ul>
<% else %>
  <p>Not yet</p>
<% end %>

app/views/pages/archive.html.erb
<% content_for :title, "Archive for #{@date}" %>
<h2>Archive for <%= @date %></h2>
<hr/>
<%= render "pages/index" %>

app/views/pages/index.html.erb
<%= render "pages/index" %>

app/views/pages/new.html.erb
<%= form_for @page do |f| %>
  <legend>Please fill required fields</legend>
  <%= bootstrap_field_wrap @page, :title do %>
    <%= f.label :title, class: "sr-only" %>
    <%= f.text_field :title, :placeholder => 'Page title', class: "form-control" %>
  <% end %>
  <%= bootstrap_field_wrap @page, :content do %>
    <%= f.label :content, class: "sr-only" %>
    <%= f.text_area :content, rows: '12', class: "form-control" %>
  <% end %>
  <%= bootstrap_field_wrap @page, :category_id do %>
    <%= f.label :category_id %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class: "form-control"}) %>
  <% end %>
  <%= f.submit "Save", :class => "btn btn-primary" %>
<% end %>

app/views/pages/show.html.erb
<% content_for :title, @page.title %>
<% render "users/about", bio: @page.user.bio %>
<div class="blog-post">
  <h2 class="blog-post-title">
    <%= @page.title %>
    <%= link_to "Edit", edit_page_path(@page), class: "btn btn-outline-primary" if owner? @page %>
    <%= link_to "Delete", page_path(@page), method: "delete", class: "btn btn-outline-danger", data: {confirm:"Are you sure?"} if owner? @page %>
  </h2>
  <p class="blog-post-meta">
    Posted at <%= @page.created_at.strftime('%B %d, %Y')%>
    by <%= link_to @page.user.name, user_path(@page.user) %>
    to <%= link_to @page.category.name, category_path(@page.category) %>
  </p>
  <%= @page.content.html_safe %>
  <hr/>
  <p class="blog-post-meta">
  <% @page.tags.each_with_index do |tag, i| %>
    <%= link_to tag.name, tag_path(tag) %><%= "," if i < @page.tags.size - 1 %>
  <% end %>
  <p>
</div>
<nav class="blog-pagination">
  <% if !@older %>
    <a class="btn btn-outline-secondary disabled" href="#">Prev</a>
  <% else %>
    <%= link_to "Prev", page_path(@older), class: "btn btn-outline-primary" %>
  <% end %>
  <% if !@newer %>
    <a class="btn btn-outline-secondary disabled" href="#">Next</a>
  <% else %>
    <%= link_to "Next", page_path(@newer), class: "btn btn-outline-primary" %>
  <% end %>
</nav>